/*
CIS 18B 
Cars Database Assignment
Daniel Marich
 */
package carsdatabaseassignmentmarich;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.ArrayList;

/**
 *
 * @author Daniel
 */
public class CarsDisplay extends javax.swing.JFrame {

    /**
     * Creates new form CarsDisplay
     */
    Connection carsDBconnection=null;
    PreparedStatement carsDBstatement=null;
    ResultSet carsResultSet=null;
    ArrayList<Car> Cars;
    int currentSelection = 0;
    
    public CarsDisplay() {
        initComponents();
        load();
    }
    
    public void connectToDB()
    {
           try
        {
        carsDBconnection = DriverManager.getConnection("jdbc:derby://localhost:1527/cars_database", "cars", "vroom");
        ResultSet carsTableData = CarQueries.getAll(carsDBconnection).executeQuery();
        Cars = new ArrayList<>();

        while (carsTableData.next())
        { 
          Cars.add(new Car(
            carsTableData.getInt("CARID"), 
            carsTableData.getString("CARMAKE"), 
            carsTableData.getString("CARMODEL"), 
            carsTableData.getString("CARYEAR"), 
            carsTableData.getInt("CARMILEAGE")));
        }

        }
        catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }


    }
    public void currentSelection(int choice)
    {
        Car temp = Cars.get( choice - 1 );
        carIDField.setText(Integer.toString(temp.getCarID()) );
        carMakeField.setText( temp.getCarMake() );      
        carModelField.setText( temp.getCarModel() );
        carYearField.setText(temp.getCarYear()) ;
        carMileageField.setText(Integer.toString( temp.getCarMileage()) );
        int size = Cars.size();
        String records = Integer.toString(size); 
        totalRecords.setText(records);
    }
    
    public void load()
    {
        this.connectToDB();
        Car temp = Cars.get( 0 );
        carIDField.setText(Integer.toString(temp.getCarID()) );
        carMakeField.setText( temp.getCarMake() );      
        carModelField.setText( temp.getCarModel() );
        carYearField.setText( temp.getCarYear()) ;
        carMileageField.setText(Integer.toString( temp.getCarMileage()) );
        String record = Integer.toString(1); 
        currentSelected.setText(record);
        int size = Cars.size();
        String records = Integer.toString(size); 
        totalRecords.setText(records);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        carModelField1 = new javax.swing.JTextField();
        carMakeField1 = new javax.swing.JTextField();
        carYearField1 = new javax.swing.JTextField();
        carMileageField1 = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cancelAddButton = new javax.swing.JButton();
        deleteDialog = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        yesDeleteButton = new javax.swing.JButton();
        cancelDeleteButton = new javax.swing.JButton();
        browseDialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        browseTextArea = new javax.swing.JTextArea();
        closeBrowseDialog = new javax.swing.JButton();
        findResultsDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        findResultsTextArea = new javax.swing.JTextArea();
        findTitle = new javax.swing.JLabel();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        currentSelected = new javax.swing.JTextField();
        totalRecords = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        carIDField = new javax.swing.JTextField();
        carModelField = new javax.swing.JTextField();
        carMakeField = new javax.swing.JTextField();
        carYearField = new javax.swing.JTextField();
        carMileageField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        findButton = new javax.swing.JButton();
        deleteRecordButton = new javax.swing.JButton();
        findField = new javax.swing.JTextField();
        browseRecordsButton = new javax.swing.JButton();
        titleMain = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        addDialog.setResizable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Add Car Record");

        jLabel8.setText("Car Mileage");

        addButton1.setText("Add");
        addButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButton1MouseClicked(evt);
            }
        });
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Car Model");

        jLabel10.setText("Car Make");

        jLabel11.setText("Car Year");

        cancelAddButton.setText("Cancel");
        cancelAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelAddButtonMouseClicked(evt);
            }
        });
        cancelAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7))
                    .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addDialogLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(addButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelAddButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addDialogLayout.createSequentialGroup()
                            .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(carMileageField1)
                                .addComponent(carYearField1)
                                .addComponent(carMakeField1)
                                .addComponent(carModelField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carMakeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carModelField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carYearField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carMileageField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton1)
                    .addComponent(cancelAddButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        deleteDialog.setAlwaysOnTop(true);
        deleteDialog.setMaximumSize(new java.awt.Dimension(341, 82));
        deleteDialog.setMinimumSize(new java.awt.Dimension(341, 82));
        deleteDialog.setResizable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Are you sure you want to delete the current record?");

        yesDeleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yesDeleteButton.setText("Yes");
        yesDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesDeleteButtonActionPerformed(evt);
            }
        });

        cancelDeleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelDeleteButton.setText("Cancel");
        cancelDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteDialogLayout = new javax.swing.GroupLayout(deleteDialog.getContentPane());
        deleteDialog.getContentPane().setLayout(deleteDialogLayout);
        deleteDialogLayout.setHorizontalGroup(
            deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesDeleteButton)
                .addGap(68, 68, 68)
                .addComponent(cancelDeleteButton)
                .addGap(62, 62, 62))
        );
        deleteDialogLayout.setVerticalGroup(
            deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cancelDeleteButton)
                    .addComponent(yesDeleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        browseDialog.setMaximumSize(new java.awt.Dimension(400, 300));
        browseDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        browseDialog.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel12.setText("Browse Records");

        browseTextArea.setColumns(20);
        browseTextArea.setRows(5);
        browseTextArea.setMaximumSize(new java.awt.Dimension(400, 200));
        browseTextArea.setMinimumSize(new java.awt.Dimension(400, 200));
        browseTextArea.setPreferredSize(new java.awt.Dimension(400, 200));
        browseTextArea.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(browseTextArea);

        closeBrowseDialog.setText("Close");
        closeBrowseDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBrowseDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout browseDialogLayout = new javax.swing.GroupLayout(browseDialog.getContentPane());
        browseDialog.getContentPane().setLayout(browseDialogLayout);
        browseDialogLayout.setHorizontalGroup(
            browseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(browseDialogLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(browseDialogLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(closeBrowseDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        browseDialogLayout.setVerticalGroup(
            browseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(closeBrowseDialog)
                .addContainerGap())
        );

        findResultsDialog.setMaximumSize(new java.awt.Dimension(356, 183));
        findResultsDialog.setMinimumSize(new java.awt.Dimension(356, 183));

        findResultsTextArea.setColumns(20);
        findResultsTextArea.setRows(5);
        jScrollPane2.setViewportView(findResultsTextArea);

        findTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        findTitle.setText("Results of Your Car Model Search");

        javax.swing.GroupLayout findResultsDialogLayout = new javax.swing.GroupLayout(findResultsDialog.getContentPane());
        findResultsDialog.getContentPane().setLayout(findResultsDialogLayout);
        findResultsDialogLayout.setHorizontalGroup(
            findResultsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findResultsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findResultsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        findResultsDialogLayout.setVerticalGroup(
            findResultsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findResultsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        previousButton.setText("Previous");
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButtonMouseClicked(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });

        currentSelected.setEditable(false);
        currentSelected.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                currentSelectedInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        totalRecords.setEditable(false);

        jLabel1.setText("of");

        jLabel2.setText("Car ID");

        jLabel3.setText("Car Model");

        jLabel4.setText("Car Make");

        jLabel5.setText("Car Year");

        jLabel6.setText("Car Mileage");

        carIDField.setEditable(false);
        carIDField.setOpaque(false);

        carModelField.setEditable(false);

        carMakeField.setEditable(false);

        carYearField.setEditable(false);

        carMileageField.setEditable(false);

        addButton.setText("Add Record");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        deleteRecordButton.setText("Delete Record");
        deleteRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordButtonActionPerformed(evt);
            }
        });

        findField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                findFieldInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        findField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFieldActionPerformed(evt);
            }
        });

        browseRecordsButton.setText("Browse Records");
        browseRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseRecordsButtonActionPerformed(evt);
            }
        });

        titleMain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleMain.setText("Cars Database Administration Program");

        jLabel14.setText("(Enter Car Model to Find)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(previousButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(totalRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nextButton)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carMileageField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(carYearField)
                                    .addComponent(carMakeField)
                                    .addComponent(carIDField)
                                    .addComponent(carModelField, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleMain)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteRecordButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseRecordsButton)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titleMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nextButton)
                    .addComponent(totalRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(currentSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carMakeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carMileageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteRecordButton)
                    .addComponent(browseRecordsButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findButton)
                    .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentSelectedInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_currentSelectedInputMethodTextChanged
        // TODO add your handling code here:
        int choice = Integer.parseInt(currentSelected.getText());
        String temp = Integer.toString(choice); 
        currentSelected.setText(temp);
        currentSelection(choice);
    }//GEN-LAST:event_currentSelectedInputMethodTextChanged

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:

        try
        {      

        ArrayList<Car> Results;
        String searchString = findField.getText();
        System.out.println("searchString = " + searchString +"\n");
        carsDBconnection = DriverManager.getConnection("jdbc:derby://localhost:1527/cars_database", "cars", "vroom");


        ResultSet resultsData = CarQueries.find(carsDBconnection, searchString).executeQuery();
        Results = new ArrayList<>();

        while (resultsData.next())
        { 
          Results.add(new Car(
            resultsData.getInt("CARID"), 
            resultsData.getString("CARMAKE"), 
            resultsData.getString("CARMODEL"), 
            resultsData.getString("CARYEAR"), 
            resultsData.getInt("CARMILEAGE")));
        }
        
        String records = "";

        for (int i = 0; i < Results.size(); i++)
        {

                records += (Results.get(i).getCarID() + "  " + Results.get(i).getCarMake() + " " + Results.get(i).getCarModel() + " " + Results.get(i).getCarYear() + " " + Results.get(i).getCarMileage() + "\n");
        }
        findResultsDialog.setVisible(true);
        findResultsTextArea.setText(records);
        
        }
        
        catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_findButtonActionPerformed

    private void previousButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseClicked
        // TODO add your handling code here:
        int prev = Integer.parseInt(currentSelected.getText());
        prev = prev -1;
        if (prev < 1) prev = 1;

        String temp = Integer.toString(prev); 
        currentSelected.setText(temp);
        currentSelection(prev);

    }//GEN-LAST:event_previousButtonMouseClicked

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        // TODO add your handling code here:
        int size = Cars.size();
        int prev = Integer.parseInt(currentSelected.getText());
        if (prev >= size) ;
        else  prev = prev + 1;

        String temp = Integer.toString(prev); 
        currentSelected.setText(temp);
        currentSelection(prev);

      

    }//GEN-LAST:event_nextButtonMouseClicked

    private void addButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton1MouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addDialog.setVisible(true);
        addDialog.setSize ( addDialog.getPreferredSize() );
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
        //get prepared statement
        
        //execute update statement
        try
        {
        String make = carMakeField1.getText();      
        String model = carModelField1.getText();
        String year = carYearField1.getText();
        int mileage = Integer.parseInt(carMileageField1.getText() );

        carsDBconnection = DriverManager.getConnection("jdbc:derby://localhost:1527/cars_database", "cars", "vroom");
        CarQueries.add(carsDBconnection, new Car(make, model, year, mileage));         
        this.load();
     
  
        }
        catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }

        addDialog.setVisible(false);

    }//GEN-LAST:event_addButton1ActionPerformed

    private void deleteRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordButtonActionPerformed
        // TODO add your handling code here:
        deleteDialog.setVisible(true);
        deleteDialog.setSize ( addDialog.getPreferredSize() );
    }//GEN-LAST:event_deleteRecordButtonActionPerformed

    private void findFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_findFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_findFieldInputMethodTextChanged

    private void findFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findFieldActionPerformed

    private void browseRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseRecordsButtonActionPerformed
        // TODO add your handling code here:
        browseDialog.setVisible(true);
        browseDialog.setSize ( addDialog.getPreferredSize() );
        //this.connectToDB();
        try
        {
         carsDBconnection = DriverManager.getConnection("jdbc:derby://localhost:1527/cars_database", "cars", "vroom");
        //ResultSet carsTableData = CarQueries.getAll(carsDBconnection).executeQuery();
        
        String records = ("");

        for (int i = 0; i < Cars.size(); i++)
        {

                records += (Cars.get(i).getCarID() + "  " + Cars.get(i).getCarMake() + " " + Cars.get(i).getCarModel() + " " + Cars.get(i).getCarYear() + " " + Cars.get(i).getCarMileage() + "\n");
        }
        browseTextArea.setText(records);

        }
        catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }
        
        
        
 
 
    }//GEN-LAST:event_browseRecordsButtonActionPerformed

    private void yesDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesDeleteButtonActionPerformed
        // TODO add your handling code here:
        try
        {           
        int choice = Integer.parseInt(currentSelected.getText());
        carsDBconnection = DriverManager.getConnection("jdbc:derby://localhost:1527/cars_database", "cars", "vroom");
        CarQueries.delete(carsDBconnection, choice);         
        this.load(); 
        deleteDialog.setVisible(false);
        }
        
        catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }
                
    }//GEN-LAST:event_yesDeleteButtonActionPerformed

    private void cancelDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDeleteButtonActionPerformed
        // TODO add your handling code here:
        deleteDialog.setVisible(false);
    }//GEN-LAST:event_cancelDeleteButtonActionPerformed

    private void cancelAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelAddButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelAddButtonMouseClicked

    private void cancelAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddButtonActionPerformed
        // TODO add your handling code here:
        addDialog.setVisible(false);
    }//GEN-LAST:event_cancelAddButtonActionPerformed

    private void closeBrowseDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBrowseDialogActionPerformed
        // TODO add your handling code here:
        browseDialog.setVisible(false);
    }//GEN-LAST:event_closeBrowseDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarsDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarsDisplay().setVisible(true);

                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JDialog addDialog;
    private javax.swing.JDialog browseDialog;
    private javax.swing.JButton browseRecordsButton;
    private javax.swing.JTextArea browseTextArea;
    private javax.swing.JButton cancelAddButton;
    private javax.swing.JButton cancelDeleteButton;
    private javax.swing.JTextField carIDField;
    private javax.swing.JTextField carMakeField;
    private javax.swing.JTextField carMakeField1;
    private javax.swing.JTextField carMileageField;
    private javax.swing.JTextField carMileageField1;
    private javax.swing.JTextField carModelField;
    private javax.swing.JTextField carModelField1;
    private javax.swing.JTextField carYearField;
    private javax.swing.JTextField carYearField1;
    private javax.swing.JButton closeBrowseDialog;
    private javax.swing.JTextField currentSelected;
    private javax.swing.JDialog deleteDialog;
    private javax.swing.JButton deleteRecordButton;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findField;
    private javax.swing.JDialog findResultsDialog;
    private javax.swing.JTextArea findResultsTextArea;
    private javax.swing.JLabel findTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel titleMain;
    private javax.swing.JTextField totalRecords;
    private javax.swing.JButton yesDeleteButton;
    // End of variables declaration//GEN-END:variables
}
